config/routes.rb
Admin::Engine.routes.draw do
  resources :languages
  resources :users
  resources :services
  resources :shards do
    resources :shard_users
    resources :shard_languages
  end
  root to: "services#index"
end

app/controllers/admin/services_controller.rb
module Admin
class ServicesController < SpaceController
  load_and_authorize_resource

  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
    @form_legend = t("admin.service.form_legend.new")

    render :form
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
    @form_legend = t("admin.service.form_legend.edit")

    render :form
  end

  def create
    @service = Service.new(params[:service])
    @form_legend = t("admin.service.form_legend.new")

    if @service.save
      redirect_to services_path, notice: t("admin.service.notice.create_success")
    else
      render :form
    end
  end

  def update
    @service = Service.find(params[:id])
    @form_legend = t("admin.service.form_legend.edit")

    if @service.update_attributes(params[:service])
      redirect_to services_path, notice: t("admin.service.notice.update_success")
    else
      render :form
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    redirect_to services_path, notice: t("admin.service.notice.delete_success")
  end

end
end

app/views/admin/services/form.html.haml
= form_for @service, html: { class: %w[ form-horizontal ] } do |service_form|
  %fieldset
    %legend= @form_legend
    = present @service, :service_form_presenter, service_form do |p|
      = p.errors
      = p.name
      = p.code
      = p.social
      = p.import_enabled
      = p.events
      = p.password_auth
      = p.actions back: services_path

app/views/admin/services/index.html.haml
%h1= t("admin.service.listing")

= render partial: "shared/flash_messages"

%br

%table.table.table-striped
  %tr
    %th= Service.human_attribute_name(:name)
    %th= Service.human_attribute_name(:code)
    %th= t("global.actions")

  - @services.each do |service|
    %tr
      %td= service.name
      %td= service.code
      %td
        = link_to t("global.edit"), edit_service_path(service), class: %w[ btn btn-mini ]
        = link_to t("global.destroy"), service,
          data: { confirm: t("global.delete_confirm") },
          method: :delete,
          class: %w[ btn btn-mini btn-danger ]

= link_to t("admin.service.new"), new_service_path, class: %w[ btn btn-primary ]