config/routes.rb
Admin::Engine.routes.draw do
  resources :languages
  resources :users
  resources :services
  resources :shards do
    resources :shard_users
    resources :shard_languages
  end
  root to: "services#index"
end

app/controllers/admin/shards_controller.rb
module Admin
class ShardsController < SpaceController
  load_and_authorize_resource
  #TODO fix this stuff - it's broken some times
  before_filter :load_settings, :only => [:new, :edit]

  def index
    @shards = Shard.all # where(user_id: current_user.id)
  end

  def show
    @shard = Shard.find(params[:id]) || not_found
  end

  def new
    @shard = Shard.new
    @form_legend = t("admin.shard.form_legend.new")

    render :form
  end

  def edit
    @shard = Shard.find_by_id(params[:id]) || not_found
    @form_legend = t("admin.shard.form_legend.edit")

    render :form
  end

  def create
    @shard = Shard.new(params[:shard])
    @form_legend = t("admin.shard.form_legend.new")

    if @shard.save
      redirect_to shards_path, notice: t("admin.shard.notice.create_success")
    else
      render :form
    end
  end

  def update
    @shard = Shard.find_by_id(params[:id]) || not_found
    @form_legend = t("admin.shard.form_legend.edit")

    if @shard.update_attributes(params[:shard])
      redirect_to shards_path, notice: t("admin.shard.notice.update_success")
    else
      render :form
    end
  end

  def destroy
    @shard = Shard.find_by_id(params[:id]) || not_found
    @shard.destroy

    redirect_to shards_path, notice: t("admin.shard.notice.delete_success")
  end
  
  private
  
  def load_settings
    @settings = Shard::SETTINGS_LIST.map{ |key|
      {key => Shard.settings[key]}
    }
  end

end
end

app/views/admin/shards/form.html.haml
= form_for @shard, html: { class: %w[ form-horizontal ] } do |shard_form|
  %fieldset
    %legend= @form_legend
    = present @shard, :shard_form_presenter, shard_form do |p|
      = p.errors
      = p.name
      = p.gem_name
      - @settings.each do |setting|
        = p.setting setting
      = p.author_features
      = p.master_features
      = p.actions back: shards_path

app/views/admin/shards/index.html.haml
%h1= t("admin.shard.listing")

= render partial: "shared/flash_messages"

%br

%table.table.table-striped
  %tr
    %th= Shard.model_name.human
    %th= t("global.actions")

  - @shards.each do |shard|
    %tr
      %td{ class: "name" }
        = shard.name
      %td{ class: "operations"}
        = link_to t("admin.shard.users"), shard_shard_users_path(shard), class: %w[ btn btn-mini ]
        = link_to t("admin.shard.languages"), shard_shard_languages_path(shard), class: %w[ btn btn-mini ]
        = link_to t("global.edit"), edit_shard_path(shard), class: %w[ btn btn-mini ]
        = link_to t("global.destroy"), shard,
          data: { confirm: t("global.delete_confirm") },
          method: :delete,
          class: %w[ btn btn-mini btn-danger ]

= link_to t("admin.shard.new"), new_shard_path, class: %w[ btn btn-primary ]