config/routes.rb
Admin::Engine.routes.draw do
  resources :languages
  resources :users
  resources :services
  resources :shards do
    resources :shard_users
    resources :shard_languages
  end
  root to: "services#index"
end

app/controllers/admin/shard_users_controller.rb
module Admin
class ShardUsersController < SpaceController
  load_and_authorize_resource class: "Assignment"
  before_filter do
    @shard = Shard.find_by_id(params[:shard_id]) || not_found
    @roles = Role.all
  end

  def index
    @shard_users = @shard.users
  end

  def new
    @form_legend = t("admin.shard_user.form_legend.new")
    @shard_user = ShardUser.new(id: nil, shard_id: @shard.id)

    render :form
  end

  def create
    @shard_user = ShardUser.new(params[:shard_user])
    @shard_user.shard_id = @shard.id
    @form_legend = t("admin.shard_user.form_legend.new")

    if @shard_user.save
      redirect_to shard_shard_users_path(@shard), notice: t("admin.shard_user.notice.create_success")
    else
      render :form
    end
  end

  def edit
    @user = User.find_by_id(params[:id]) || not_found
    @shard_user = ShardUser.get(@user, @shard)

    @form_legend = t("admin.shard_user.form_legend.edit")
    @roles = Role.all

    render :form
  end

  def update
    @user = User.find_by_id(params[:id]) || not_found
    @shard_user = ShardUser.get(@user, @shard) || not_found
    @form_legend = t("admin.shard_user.form_legend.edit")

    if @shard_user.update_attributes(params[:shard_user])
      redirect_to shard_shard_users_path(@shard), notice: t("admin.shard_user.notice.update_success")
    else
      render :form
    end
  end

  def destroy
    @user = User.find_by_id(params[:id]) || not_found
    @shard_user = ShardUser.get(@user, @shard) || not_found
    @shard_user.destroy

    redirect_to shard_shard_users_path(@shard), notice: t("admin.shard_user.notice.delete_success")
  end

end
end

app/views/admin/shard_users/form.html.haml
= form_for [@shard, @shard_user], html: { class: %w[ form-horizontal ] } do |shard_user_form|
  %fieldset
    %legend= @form_legend
    = present @shard_user, :shard_user_form_presenter, shard_user_form do |p|
      = p.email
      = p.roles @roles
      = p.actions back: shard_shard_users_path(@shard)

app/views/admin/shard_users/index.html.haml
%h1= t("admin.shard_user.listing")

= render partial: "shared/flash_messages"

%br

%table.table.table-striped
  %tr
    %th= User.model_name.human
    %th= t("global.actions")

  - @shard_users.each do |user|
    %tr
      %td{ class: "name" }
        = user.email
        &mdash;
        = user.roles_for_shard(@shard).map{ |role| t("admin.role.#{role.name}") }.join(", ")
      %td{ class: "operations" }
        = link_to t("global.edit"), edit_shard_shard_user_path(@shard, user), class: %w[ btn btn-mini ]
        = link_to t("global.destroy"), shard_shard_user_path(@shard, user.id),
          data: { confirm: t("global.delete_confirm") },
          method: :delete,
          class: %w[ btn btn-mini btn-danger ]

= link_to t("admin.shard_user.new"), new_shard_shard_user_path, class: %w[ btn btn-primary ]